project:
  type: website
  output-dir: docs

website:
  title: "LSE GV4L3"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - introduction.qmd
      - topic1.qmd
      - topic2.qmd
      - topic3.qmd
      - topic4.qmd
      - topic5.qmd

execute:
  freeze: auto

format:
  html:
    theme: 
      light: cyborg
      dark: cyborg
    css: styles.css
    toc: true
    font-family: sans-serif



